apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: smart-inventory
    app.kubernetes.io/component: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: smart-inventory
  ports:
  - port: 9090
    targetPort: 9090
    name: web
  type: ClusterIP