apiVersion: v1
kind: Secret
metadata:
  name: postgres-exporter-secret
  namespace: monitoring
  labels:
    app.kubernetes.io/name: postgres-exporter
    app.kubernetes.io/part-of: smart-inventory
    app.kubernetes.io/component: monitoring
type: Opaque
stringData:
  DATA_SOURCE_NAME: "postgresql://postgres:ProdSecurePassword2026!@smart-inventory-db.default.svc.cluster.local:5432/inventory_prod?sslmode=disable"