import { useState, useEffect } from 'react';
import { FileSpreadsheet, FileText, Download, BarChart3, AlertTriangle, ShoppingCart, Package } from 'lucide-react';
import { formatDate } from '../utils/helpers.js';
import api from '../services/api.js';
import { useToast } from '../context/ToastContext.jsx';
import AnimatedPage from '../components/layout/AnimatedPage.jsx';

const reportTypes = [
  { type: 'inventory', label: 'Inventory Report', desc: 'Complete list of all products with stock levels, prices, and values', icon: Package, color: '#4361ee' },
  { type: 'sales', label: 'Sales Report', desc: 'All completed sale orders with revenue breakdown', icon: BarChart3, color: '#10b981' },
  { type: 'purchases', label: 'Purchase Report', desc: 'Purchase orders and supplier spending analysis', icon: ShoppingCart, color: '#7c3aed' },
  { type: 'alerts', label: 'Alerts Report', desc: 'Stock alert history with severity and resolution status', icon: AlertTriangle, color: '#f59e0b' },
];

export default function Reports() {
  const toast = useToast();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState('');

  const fetchReports = async () => {
    try {
      const { data } = await api.get('/reports');
      setReports(data.data.reports || []);
    } catch (e) { console.error(e); }
    finally { setLoading(false); }
  };

  useEffect(() => { fetchReports(); }, []);

  const generateReport = async (type) => {
    setGenerating(type);
    try {
      await api.post('/reports/generate', { type, format: 'excel' });
      toast.success('Report generated successfully');
      fetchReports();
    } catch (e) { toast.error(e.response?.data?.message || 'Error generating report'); }
    finally { setGenerating(''); }
  };

  const downloadReport = async (id, title) => {
    try {
      const response = await api.get(`/reports/${id}/download`, { responseType: 'blob' });
      const url = window.URL.createObjectURL(new Blob([response.data]));
      const link = document.createElement('a');
      link.href = url;
      link.setAttribute('download', `${title.replace(/\s/g, '_')}.xlsx`);
      document.body.appendChild(link);
      link.click();
      link.remove();
      window.URL.revokeObjectURL(url);
    } catch (e) { toast.error('Download failed'); }
  };

  return (
    <AnimatedPage>
    <div>
      <div className="page-header">
        <div>
          <h1 className="page-title">Reports</h1>
          <p className="page-subtitle">Generate and download reports</p>
        </div>
      </div>

      <div className="reports-grid">
        {reportTypes.map(rt => (
          <div key={rt.type} className="report-type-card" onClick={() => generateReport(rt.type)}>
            <div className="report-type-icon" style={{ background: `${rt.color}18`, color: rt.color }}>
              <rt.icon size={22} />
            </div>
            <h4>{rt.label}</h4>
            <p>{rt.desc}</p>
            {generating === rt.type && (
              <div style={{ marginTop: 10, display: 'flex', alignItems: 'center', gap: 6, fontSize: 12, color: rt.color }}>
                <div className="loader-spinner" style={{ width: 14, height: 14, borderWidth: 2 }} /> Generating...
              </div>
            )}
          </div>
        ))}
      </div>

      <div className="data-table-container">
        <div className="data-table-header">
          <div className="data-table-title">Generated Reports</div>
        </div>
        <div className="table-wrapper">
          <table className="data-table">
            <thead>
              <tr><th>Report</th><th>Type</th><th>Format</th><th>Generated By</th><th>Date</th><th>Action</th></tr>
            </thead>
            <tbody>
              {loading ? Array.from({ length: 3 }).map((_, i) => (
                <tr key={i}><td colSpan="6"><div className="skeleton skeleton-text" /></td></tr>
              )) : reports.length === 0 ? (
                <tr><td colSpan="6" style={{ textAlign: 'center', padding: 40, color: 'var(--text-muted)' }}>No reports generated yet</td></tr>
              ) : reports.map(r => (
                <tr key={r.id}>
                  <td style={{ fontWeight: 600 }}>{r.title}</td>
                  <td><span className="badge badge-info">{r.type}</span></td>
                  <td>
                    <span style={{ display: 'flex', alignItems: 'center', gap: 4, color: 'var(--text-secondary)' }}>
                      <FileSpreadsheet size={14} /> {r.format?.toUpperCase()}
                    </span>
                  </td>
                  <td style={{ color: 'var(--text-secondary)' }}>{r.generatedByUser?.name || 'System'}</td>
                  <td style={{ fontSize: 12, color: 'var(--text-muted)' }}>{formatDate(r.createdAt)}</td>
                  <td>
                    <button className="btn btn-primary" style={{ padding: '4px 12px', fontSize: 11 }} onClick={() => downloadReport(r.id, r.title)}>
                      <Download size={12} /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    </AnimatedPage>
  );
}
